modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power_template"
version="15"
displayName="Keepers of the Stones II: Addon Template"
displayURL="https://mcreator.net"
credits="Created by Environment Studios"
authors="Environment Studios"
description="This is template workspace for creating custom stones  "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.power_template]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.237,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.power_template]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.power_template]]
    modId="power"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power_template]]
    modId="pehkui"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power_template]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power_template]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power_template]]
    modId="cpapi_local"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration