modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power_template"
version="7"
displayName="KotS II: Addon Template"
displayURL="https://mcreator.net"
credits="Created by Environment Studios"
authors="Environment Studios"
description="This is template workspace for creating custom stones  "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.power_template]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.power_template]]
    modId="power"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power_template]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power_template]]
    modId="cpapi"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

